### ISSUE TITLE
Files ending with a comment fail to highlight in SQ 5.2 and fail overall analysis

### ISSUE THREAD

**Issue by dbolkensteyn** [SonarQubeCommunity/sonar-css#147] opened 2015-11-10 07:35 UTC
If a file ends with a comment, the CSS highlighting fails in SonarQube 5.2, which in turns fails the overall anaylsis:

```
body {}
/*foo*/
```

will lead to the following error:

```
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
Total time: 2.522s
Final Memory: 11M/322M
INFO: ------------------------------------------------------------------------
ERROR: Error during Sonar runner execution
ERROR: Unable to execute Sonar
ERROR: Caused by: Unable to analyze file: C:\Users\dinesh\Desktop\sonarsource\sonar-examples\projects\languages\css\css-sonar-runner\src\Site.css
ERROR: Caused by: Unable to highlight file [moduleKey=org.sonarqube:css-simple-sq-runner, relative=src/Site.css, basedir=C:\Users\dinesh\Desktop\sonarsource\sonar-examples\projects\languages\css\css-sonar-runner] from offset 12 to offset 19

ERROR: Caused by: 19 is not a valid offset for file [moduleKey=org.sonarqube:css-simple-sq-runner, relative=src/Site.css, basedir=C:\Users\dinesh\Desktop\sonarsource\sonar-examples\projects\languages\css\css-sonar-runner]. Max offset is 18
```

This bug was initially reported on StackOverflow: http://stackoverflow.com/questions/33551357/5-2-upgrade-illegalargumentexception-unable-to-highlight-file

**Comment by dbolkensteyn** [comment] 2015-11-10 07:40
let me know if you need help fixing this @kalidasya @racodond - as this bug leads to the overall project analysis failure, I think it would be nice to fix it ASAP.

**Comment by racodond** [comment] 2015-11-10 14:50
@dbolkensteyn I cannot reproduce. Could you please provide the file to reproduce?

**Comment by dbolkensteyn** [comment] 2015-11-10 15:09
Strange.. here's the file (rename it in .css) [Site.txt](https://github.com/SonarCommunity/sonar-css/files/30926/Site.txt)

**Comment by dbolkensteyn** [comment] 2015-11-10 15:11
I'm running the analysis from a Windows machine - didn't try from Mac or Linux - if that makes a difference perhaps. I'm doing the analysis by dropping that file in the "src" folder of https://github.com/SonarSource/sonar-examples/tree/master/projects/languages/css/css-sonar-runner

**Comment by racodond** [comment] 2015-11-10 15:22
> Strange.. here's the file (rename it in .css) Site.txt

The analysis succeeds on Linux. But the syntax highlighting is not perfect due to the presence of the BOM. The presence of the BOM might lead to some issues because it corrupts the syntax highlighting position the way it is currently code. See the thread I opened today about this topic:  https://groups.google.com/d/msg/sonarqube/u98klcXNGA0/lq1qOloLCAAJ. All the plugins seem to face the same issue with the BOM file. So, it could be nice if somebody at SonarSource could answer the thread to explain how they plan to deal with BOM in syntax highlighting.

Thanks

David

**Comment by racodond** [comment] 2015-11-16 10:58
@dbolkensteyn None of the SonarSource plugins is currently properly supporting BOM: https://groups.google.com/d/msg/sonarqube/u98klcXNGA0/rHrBru0XAQAJ. With version 5.2, it sometimes lead to crashes: https://groups.google.com/d/msg/sonarqube/uib5tcHH-gE/dTdrb9u-CAAJ. So, I'm gonna wait for one of the SonarSource plugins to be fixed and I'll apply the patch on the CSS plugin right after.

**Comment by vilchik-elena** [comment] 2015-11-16 12:55
@racodond We've fixed XML (but probably it's not best place to understand logic), see https://github.com/SonarCommunity/sonar-xml/blob/master/sonar-xml-plugin/src/main/java/org/sonar/plugins/xml/checks/XmlFile.java#L98 
Actually solution is the following one: check if there is BOM in the file and if there is add "-1" here https://github.com/SonarCommunity/sonar-css/blob/4ca244cd65d739800917ecedc517e94d0c3bc6b2/css-squid/src/main/java/org/sonar/css/ast/visitors/SyntaxHighlighterVisitor.java#L119

**Comment by dbolkensteyn** [comment] 2015-11-16 13:08
IMO @racodond you can easily add a very similar logic of checking if the first character is a BOM in https://github.com/SonarCommunity/sonar-css/blob/master/css-squid/src/main/java/org/sonar/css/ast/visitors/SyntaxHighlighterVisitor.java#L86 before constructing the line offsets array

as @henryju mentioned, the server fully removes that character, and it therefore doesn't not contribute towards the offset calculation.

**Comment by henryju** [comment] 2015-11-16 13:21
@vilchik-elena Can't you simply use an Apache commons BOMInputStream when reading file content to be sure the BOM is properly skipped?
See: https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/batch/fs/internal/FileMetadata.java#L295

**Comment by racodond** [comment] 2015-11-16 13:24
I'll do what I said: "So, I'm gonna wait for one of the SonarSource plugins to be fixed and I'll apply the patch on the CSS plugin right after". But I'm not paid by SonarSource and contribute for free. So, there's no hurry. Moreover, all the plugins but XML crashes the same way for now.

**Comment by dbolkensteyn** [comment] 2015-11-16 18:28
Yes it makes sense @racodond to wait for the proper fix to be implemented somewhere. There is no real urgency on getting a bug fix version of the CSS plugin out there.

My main point was in fact to not copy the XML's solution and introduce a `CssFile`... seems like the `BOMInputStream` is indeed a superior approach.

**Comment by racodond** [comment] 2015-11-27 10:20
@dbolkensteyn Any idea when it would be implemented in one of your plugins? Any JIRA ticket that I could follow to get notified?

**Comment by rupreck** [comment] 2016-01-03 21:57
Indeed, this is a showstopper for all our analysis. It needs urgent attention because sonar won't analyse any of our projects out of TFS due to this bug (in javascript files).

**Comment by dbolkensteyn** [comment] 2016-01-04 08:06
@rupreck Javascript has this ticket: https://jira.sonarsource.com/browse/SONARJS-546

**Comment by rupreck** [comment] 2016-01-05 09:05
Thanks for escalating. We resolved by stripping BOM's from all CSS, CSHTML, CS, XML and JS files before analysis.  This simple routine will do it:

```cs
    // Byte order marks are removed from all files since 5.2 as they kill analysis.
    RemoveBomsFromFilesRecursively(solutionPath, "*.cs");
    RemoveBomsFromFilesRecursively(solutionPath, "*.cshtml");
    RemoveBomsFromFilesRecursively(solutionPath, "*.js");
    RemoveBomsFromFilesRecursively(solutionPath, "*.css");
    RemoveBomsFromFilesRecursively(solutionPath, "*.xml");

        /// <summary>
        /// Strips the BOM's from files starting from the specified directory
        /// </summary>
        /// <param name="rootDirectory">Root directory to search</param>
        /// <param name="filePattern">Search pattern eg. *.cs or *.*</param>
        public static void RemoveBomsFromFilesRecursively(string rootDirectory, string filePattern)
        {
            foreach (string directory in Directory.GetDirectories(rootDirectory))
            {
                foreach (string filename in Directory.GetFiles(directory, filePattern))
                {
                    var bytes = File.ReadAllBytes(filename);
                    if (bytes.Length > 2 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF)
                    {
                        File.WriteAllBytes(filename, bytes.Skip(3).ToArray());
                    }
                }
                RemoveBomsFromFilesRecursively(directory, filePattern);
            }
        }
```

**Comment by FJLopezGarcia** [comment] 2016-03-03 09:25
Hi @racodond, Do you have any update about the plugin fix? do you have an estimate to be completed?
Thanks a lot!!

**Comment by racodond** [comment] 2016-03-05 17:21
Fixed in https://github.com/SonarQubeCommunity/sonar-css/commit/cbb34fa7fbc7aef904ebef007f8f630695ee559c
cc @FJLopezGarcia

**Closed by racodond** 2016-03-05 17:21 UTC
Labels: bug
